import nodemailer from 'nodemailer'

export const transporter = nodemailer.createTransport({
    // host: "smtp.spatay.com",
    // port: 465,
    // secure: true,
    service:"gmail",
    auth: {
      user: process.env.SMTP_EMAIL as string,
      // this password is generated by app password 
      pass: process.env.SMTP_PASSWORD  as string
    },  
});



// const sendMail = async () => {
//     const mailOptions = {
//       from: 'your_email@gmail.com',
//       to: 'recipient@example.com',
//       subject: 'Test Email from Nodemailer and TypeScript',
//       text: 'Hello, this is a test email sent from Nodemailer with TypeScript!',
//     };
  
//     try {
//       const info = await transporter.sendMail(mailOptions);
//       console.log('Email sent:', info.response);
//     } catch (error) {
//       console.log('Error sending email:', error);
//     }
//   };
  
//   sendMail();

export const sendMail = async (to:any,subject:string,html:string,text?:string) => {
  const mailOptions = {
    from:process.env.SMTP_EMAIL as string,
    to:[to],
    subject,
    text,
    html,
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Email sent:', info.response);
  } catch (error) {
    console.log('Error sending email:', error);
  }
}